#!/bin/bash
# FitFlow Pro - Mobile Device Network Configuration Fix
# This script automatically configures the API URL for mobile device testing

set -e

echo "=================================================="
echo "FitFlow Pro - Mobile Network Configuration"
echo "=================================================="
echo ""

# Find local IP address
echo "[1/4] Detecting your computer's local IP address..."
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux
    LOCAL_IP=$(ip addr show | grep "inet " | grep -v 127.0.0.1 | head -1 | awk '{print $2}' | cut -d'/' -f1)
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    LOCAL_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | head -1 | awk '{print $2}')
else
    echo "❌ Unsupported OS: $OSTYPE"
    echo "Please manually find your IP address and create .env file:"
    echo "  echo 'FITFLOW_API_URL=http://YOUR_IP:3000' > .env"
    exit 1
fi

if [ -z "$LOCAL_IP" ]; then
    echo "❌ Could not detect local IP address"
    echo "Please manually find your IP address:"
    echo "  Linux/Mac: ip addr show | grep inet"
    echo "  Windows: ipconfig"
    exit 1
fi

echo "✅ Local IP detected: $LOCAL_IP"
echo ""

# Check if backend is running
echo "[2/4] Checking if backend is running..."
if lsof -i :3000 > /dev/null 2>&1; then
    echo "✅ Backend is running on port 3000"
else
    echo "⚠️  Backend not detected on port 3000"
    echo "Please start the backend server:"
    echo "  cd ../backend"
    echo "  npm run dev"
    echo ""
    read -p "Press Enter to continue anyway, or Ctrl+C to exit..."
fi
echo ""

# Test backend connectivity
echo "[3/4] Testing backend connectivity..."
if curl -s -f "http://$LOCAL_IP:3000/health" > /dev/null 2>&1; then
    echo "✅ Backend is accessible at http://$LOCAL_IP:3000"
else
    echo "⚠️  Cannot reach backend at http://$LOCAL_IP:3000"
    echo "Possible issues:"
    echo "  - Backend not running"
    echo "  - Firewall blocking port 3000"
    echo "  - Wrong network interface"
    echo ""
    echo "To fix firewall (Linux):"
    echo "  sudo ufw allow 3000"
    echo ""
    read -p "Press Enter to continue anyway, or Ctrl+C to exit..."
fi
echo ""

# Create .env file
echo "[4/4] Creating .env file..."
ENV_FILE=".env"
API_URL="http://$LOCAL_IP:3000"

cat > "$ENV_FILE" << EOF
# FitFlow Pro - Mobile App Configuration
# Auto-generated by fix_mobile_network.sh on $(date)

# Backend API URL for mobile device testing
# Your computer's IP: $LOCAL_IP
FITFLOW_API_URL=$API_URL

# This configuration allows your mobile device to connect to the backend
# Make sure your phone is on the same WiFi network as this computer.
EOF

echo "✅ Created $ENV_FILE with API URL: $API_URL"
echo ""

# Show summary
echo "=================================================="
echo "Configuration Complete!"
echo "=================================================="
echo ""
echo "API URL: $API_URL"
echo ""
echo "Next steps:"
echo "  1. Ensure your mobile device is on the same WiFi network"
echo "  2. Restart Expo dev server:"
echo "     npm run dev"
echo "  3. Scan QR code from Expo Go app on your phone"
echo "  4. Try registering a new user"
echo ""
echo "To test connectivity from another terminal:"
echo "  curl $API_URL/health"
echo ""
echo "For troubleshooting, see:"
echo "  /home/asigator/fitness2025/NETWORK_DEBUGGING_GUIDE.md"
echo ""
