-- FitFlow Pro Exercise Library Seed Data
-- 100+ exercises with muscle groups, equipment, and defaults
-- Based on Renaissance Periodization methodology

-- CHEST EXERCISES (14 exercises)
INSERT INTO exercises (name, muscle_groups, equipment, difficulty, default_sets, default_reps, default_rir, notes)
VALUES
  ('Barbell Bench Press', '["chest", "front_delts", "triceps"]', 'barbell', 'intermediate', 4, '6-8', 2, 'Arch back, retract scapula, bar to mid-chest'),
  ('Incline Barbell Bench Press', '["chest", "front_delts", "triceps"]', 'barbell', 'intermediate', 4, '6-8', 2, '30-45 degree incline, focus upper chest'),
  ('Dumbbell Bench Press', '["chest", "front_delts", "triceps"]', 'dumbbell', 'beginner', 4, '8-10', 2, 'Greater ROM than barbell, control descent'),
  ('Incline Dumbbell Press', '["chest", "front_delts", "triceps"]', 'dumbbell', 'beginner', 4, '8-10', 2, 'Emphasizes upper chest, neutral or pronated grip'),
  ('Cable Flyes', '["chest"]', 'cable', 'beginner', 3, '10-12', 2, 'Constant tension, full stretch at bottom'),
  ('Dumbbell Flyes', '["chest"]', 'dumbbell', 'intermediate', 3, '10-12', 2, 'Control eccentric, slight elbow bend throughout'),
  ('Machine Chest Press', '["chest", "front_delts", "triceps"]', 'machine', 'beginner', 3, '8-10', 2, 'Stable movement pattern, good for drop sets'),
  ('Pec Deck', '["chest"]', 'machine', 'beginner', 3, '12-15', 2, 'Isolation exercise, squeeze at peak contraction'),
  ('Push-ups', '["chest", "front_delts", "triceps"]', 'bodyweight', 'beginner', 3, '10-15', 2, 'Full ROM, maintain plank position'),
  ('Decline Barbell Bench Press', '["chest", "triceps"]', 'barbell', 'intermediate', 3, '8-10', 2, 'Emphasizes lower chest, careful setup'),
  ('Decline Dumbbell Press', '["chest", "triceps"]', 'dumbbell', 'intermediate', 3, '8-10', 2, 'Lower chest focus, secure foot position'),
  ('Low Cable Flyes', '["chest"]', 'cable', 'beginner', 3, '12-15', 2, 'Targets lower chest, upward motion'),
  ('Dips (Chest Focused)', '["chest", "front_delts", "triceps"]', 'bodyweight', 'intermediate', 3, '8-12', 2, 'Lean forward 30 degrees, wide grip'),
  ('Landmine Press', '["chest", "front_delts", "triceps"]', 'barbell', 'intermediate', 3, '10-12', 2, 'Single arm or two-handed, diagonal pressing angle'),

-- BACK EXERCISES (18 exercises)
  ('Conventional Deadlift', '["lower_back", "glutes", "hamstrings", "traps"]', 'barbell', 'advanced', 3, '5-6', 2, 'Hip hinge, neutral spine, brace core'),
  ('Barbell Row', '["lats", "rhomboids", "traps", "rear_delts"]', 'barbell', 'intermediate', 4, '8-10', 2, 'Hip hinge position, pull to lower chest'),
  ('Pull-ups', '["lats", "biceps"]', 'bodyweight', 'intermediate', 4, '6-10', 2, 'Full hang to chin over bar, controlled descent'),
  ('Lat Pulldown', '["lats", "biceps"]', 'machine', 'beginner', 4, '10-12', 2, 'Pull to upper chest, retract scapula'),
  ('T-Bar Row', '["lats", "rhomboids", "traps"]', 'barbell', 'intermediate', 4, '8-10', 2, 'Chest supported or free-standing, neutral spine'),
  ('Dumbbell Row', '["lats", "rhomboids", "rear_delts"]', 'dumbbell', 'beginner', 4, '10-12', 2, 'Single arm, bench supported, full stretch'),
  ('Seated Cable Row', '["lats", "rhomboids", "traps"]', 'cable', 'beginner', 4, '10-12', 2, 'Chest up, pull to sternum, squeeze shoulder blades'),
  ('Face Pulls', '["rear_delts", "traps", "rhomboids"]', 'cable', 'beginner', 3, '15-20', 3, 'Pull to face level, external rotation at end'),
  ('Chin-ups', '["lats", "biceps"]', 'bodyweight', 'intermediate', 4, '6-10', 2, 'Supinated grip, full ROM, excellent bicep stimulus'),
  ('Chest Supported Row', '["lats", "rhomboids", "traps"]', 'machine', 'beginner', 4, '10-12', 2, 'Eliminates lower back fatigue, strict form'),
  ('Meadows Row', '["lats", "rhomboids"]', 'barbell', 'advanced', 3, '10-12', 2, 'Single arm T-bar row, significant stretch'),
  ('Straight Arm Pulldown', '["lats"]', 'cable', 'beginner', 3, '12-15', 2, 'Keep arms straight, pull through lats only'),
  ('Wide Grip Pulldown', '["lats", "teres_major"]', 'machine', 'beginner', 4, '10-12', 2, 'Emphasizes lat width, pull to collarbone'),
  ('Rack Pulls', '["lower_back", "traps", "glutes"]', 'barbell', 'intermediate', 3, '6-8', 2, 'Partial deadlift, heavy loads, knee to mid-shin height'),
  ('Inverted Rows', '["lats", "rhomboids", "biceps"]', 'bodyweight', 'beginner', 3, '10-15', 2, 'Horizontal bodyweight row, adjustable difficulty'),
  ('Machine High Row', '["lats", "traps", "rear_delts"]', 'machine', 'beginner', 3, '10-12', 2, 'Pull to upper chest, lat focus'),
  ('Pendlay Row', '["lats", "rhomboids", "traps"]', 'barbell', 'advanced', 4, '6-8', 2, 'Dead stop each rep, explosive concentric'),
  ('Kroc Row', '["lats", "traps", "grip"]', 'dumbbell', 'advanced', 3, '15-20', 3, 'Heavy dumbbell, controlled cheating, high reps'),

-- SHOULDER EXERCISES (16 exercises)
  ('Overhead Press', '["front_delts", "triceps"]', 'barbell', 'intermediate', 4, '6-8', 2, 'Standing or seated, press straight overhead'),
  ('Dumbbell Shoulder Press', '["front_delts", "triceps"]', 'dumbbell', 'beginner', 4, '8-10', 2, 'Seated or standing, neutral or pronated grip'),
  ('Lateral Raises', '["side_delts"]', 'dumbbell', 'beginner', 3, '12-15', 2, 'Slight forward lean, thumbs slightly down at top'),
  ('Front Raises', '["front_delts"]', 'dumbbell', 'beginner', 3, '12-15', 3, 'Alternate arms or simultaneous, to eye level'),
  ('Rear Delt Flyes', '["rear_delts"]', 'dumbbell', 'beginner', 3, '15-20', 2, 'Bent over or seated, squeeze shoulder blades'),
  ('Arnold Press', '["front_delts", "side_delts", "triceps"]', 'dumbbell', 'intermediate', 3, '10-12', 2, 'Rotation from supinated to pronated'),
  ('Cable Lateral Raises', '["side_delts"]', 'cable', 'beginner', 3, '12-15', 2, 'Constant tension, cross-body or single arm'),
  ('Machine Shoulder Press', '["front_delts", "triceps"]', 'machine', 'beginner', 4, '8-10', 2, 'Controlled movement, good for failure sets'),
  ('Upright Rows', '["side_delts", "traps"]', 'barbell', 'intermediate', 3, '10-12', 2, 'Pull elbows high and wide, barbell or dumbbells'),
  ('Face Pulls (Shoulder Focus)', '["rear_delts", "traps"]', 'cable', 'beginner', 3, '15-20', 2, 'High reps, external rotation, rear delt pump'),
  ('Reverse Pec Deck', '["rear_delts"]', 'machine', 'beginner', 3, '12-15', 2, 'Isolation for rear delts, strict form'),
  ('Pike Push-ups', '["front_delts", "triceps"]', 'bodyweight', 'beginner', 3, '10-15', 2, 'Elevated hips, shoulders over hands'),
  ('Landmine Press (Shoulder)', '["front_delts", "triceps"]', 'barbell', 'intermediate', 3, '10-12', 2, 'Single arm, vertical pressing angle'),
  ('Dumbbell Z Press', '["front_delts", "triceps", "core"]', 'dumbbell', 'advanced', 3, '8-10', 2, 'Seated on floor, no leg drive, core stability'),
  ('Machine Lateral Raise', '["side_delts"]', 'machine', 'beginner', 3, '12-15', 2, 'Constant resistance, good for drop sets'),
  ('Bradford Press', '["front_delts", "side_delts", "triceps"]', 'barbell', 'advanced', 3, '10-12', 2, 'Front to back overhead movement, continuous tension'),

-- LEG EXERCISES (22 exercises)
  ('Barbell Back Squat', '["quads", "glutes", "hamstrings"]', 'barbell', 'intermediate', 4, '6-8', 2, 'Break at hips and knees, depth to parallel or below'),
  ('Romanian Deadlift', '["hamstrings", "glutes", "lower_back"]', 'barbell', 'intermediate', 3, '8-10', 2, 'Hinge at hips, maintain neutral spine, slight knee bend'),
  ('Leg Press', '["quads", "glutes"]', 'machine', 'beginner', 4, '10-12', 2, 'Full ROM, knees track over toes'),
  ('Walking Lunges', '["quads", "glutes", "hamstrings"]', 'dumbbell', 'intermediate', 3, '10-12', 2, 'Long stride, knee to 90 degrees, upright torso'),
  ('Leg Curls', '["hamstrings"]', 'machine', 'beginner', 3, '10-12', 2, 'Lying or seated, full ROM, controlled tempo'),
  ('Leg Extensions', '["quads"]', 'machine', 'beginner', 3, '10-12', 2, 'Isolation exercise, peak contraction squeeze'),
  ('Bulgarian Split Squat', '["quads", "glutes"]', 'dumbbell', 'intermediate', 3, '10-12', 2, 'Rear foot elevated, front knee tracks over toes'),
  ('Front Squat', '["quads", "core"]', 'barbell', 'advanced', 4, '6-8', 2, 'Upright torso, elbows high, quad dominant'),
  ('Sumo Deadlift', '["glutes", "hamstrings", "adductors", "lower_back"]', 'barbell', 'intermediate', 3, '6-8', 2, 'Wide stance, toes out, upright torso'),
  ('Goblet Squat', '["quads", "glutes"]', 'dumbbell', 'beginner', 3, '12-15', 2, 'Dumbbell or kettlebell at chest, upright position'),
  ('Hack Squat', '["quads", "glutes"]', 'machine', 'beginner', 4, '10-12', 2, 'Feet forward, quad emphasis, stable movement'),
  ('Glute Ham Raise', '["hamstrings", "glutes"]', 'bodyweight', 'advanced', 3, '8-10', 2, 'Full eccentric control, excellent hamstring builder'),
  ('Step-ups', '["quads", "glutes"]', 'dumbbell', 'beginner', 3, '12-15', 2, 'Box height knee to 90 degrees, drive through heel'),
  ('Smith Machine Squat', '["quads", "glutes"]', 'machine', 'beginner', 4, '8-10', 2, 'Feet forward, controlled path, various foot positions'),
  ('Nordic Curls', '["hamstrings"]', 'bodyweight', 'advanced', 3, '5-8', 2, 'Eccentric focused, partner assisted or band assisted'),
  ('Sissy Squat', '["quads"]', 'bodyweight', 'intermediate', 3, '10-15', 2, 'Lean back, knee extension focus, extreme quad stretch'),
  ('Dumbbell Romanian Deadlift', '["hamstrings", "glutes", "lower_back"]', 'dumbbell', 'beginner', 3, '10-12', 2, 'Hip hinge, maintain neutral spine'),
  ('Reverse Lunges', '["quads", "glutes"]', 'dumbbell', 'beginner', 3, '10-12', 2, 'Step back, front knee stable, upright torso'),
  ('Single Leg Press', '["quads", "glutes"]', 'machine', 'intermediate', 3, '12-15', 2, 'Address imbalances, focus on weaker leg'),
  ('Box Squat', '["quads", "glutes", "hamstrings"]', 'barbell', 'intermediate', 4, '6-8', 2, 'Sit back to box, explosive concentric'),
  ('Zercher Squat', '["quads", "glutes", "core"]', 'barbell', 'advanced', 3, '8-10', 2, 'Bar in elbow crease, upright torso, core challenge'),
  ('Belt Squat', '["quads", "glutes"]', 'machine', 'intermediate', 4, '10-12', 2, 'Reduces spinal load, high volume work'),

-- GLUTE/HIP EXERCISES (8 exercises)
  ('Hip Thrust', '["glutes", "hamstrings"]', 'barbell', 'beginner', 4, '10-12', 2, 'Shoulders on bench, drive through heels, squeeze glutes'),
  ('Cable Pull-through', '["glutes", "hamstrings"]', 'cable', 'beginner', 3, '12-15', 2, 'Hip hinge pattern, arms straight, glute squeeze'),
  ('Glute Bridge', '["glutes"]', 'bodyweight', 'beginner', 3, '15-20', 2, 'Shoulders on floor, squeeze glutes at top'),
  ('Single Leg Hip Thrust', '["glutes", "hamstrings"]', 'dumbbell', 'intermediate', 3, '12-15', 2, 'Unilateral focus, address imbalances'),
  ('Frog Pumps', '["glutes"]', 'bodyweight', 'beginner', 3, '20-30', 3, 'Soles of feet together, high rep pump work'),
  ('B-Stance Hip Thrust', '["glutes"]', 'barbell', 'intermediate', 3, '12-15', 2, 'One foot primary, one kickstand, unilateral bias'),
  ('Donkey Kicks', '["glutes"]', 'bodyweight', 'beginner', 3, '15-20', 2, 'Knee bent 90 degrees, drive heel to ceiling'),
  ('Reverse Hyperextension', '["glutes", "hamstrings", "lower_back"]', 'machine', 'beginner', 3, '12-15', 2, 'Legs swing up, squeeze glutes, spinal traction'),

-- CALF EXERCISES (4 exercises)
  ('Standing Calf Raise', '["calves"]', 'machine', 'beginner', 4, '12-15', 2, 'Full ROM, stretch at bottom, squeeze at top'),
  ('Seated Calf Raise', '["calves"]', 'machine', 'beginner', 4, '15-20', 2, 'Targets soleus, knees bent, slow tempo'),
  ('Leg Press Calf Raise', '["calves"]', 'machine', 'beginner', 3, '12-15', 2, 'Toes on edge of platform, full stretch'),
  ('Single Leg Calf Raise', '["calves"]', 'bodyweight', 'beginner', 3, '15-20', 2, 'Balance on one foot, hold dumbbell for load'),

-- ARM EXERCISES - BICEPS (10 exercises)
  ('Barbell Curl', '["biceps"]', 'barbell', 'beginner', 3, '8-10', 2, 'Supinated grip, elbows stable, control eccentric'),
  ('Dumbbell Curl', '["biceps"]', 'dumbbell', 'beginner', 3, '10-12', 2, 'Alternate or simultaneous, full supination'),
  ('Hammer Curl', '["biceps", "brachialis", "forearms"]', 'dumbbell', 'beginner', 3, '10-12', 2, 'Neutral grip throughout, targets brachialis'),
  ('Preacher Curl', '["biceps"]', 'barbell', 'intermediate', 3, '10-12', 2, 'Isolates biceps, strict form, arm on pad'),
  ('Cable Curl', '["biceps"]', 'cable', 'beginner', 3, '12-15', 2, 'Constant tension, various attachments'),
  ('Concentration Curl', '["biceps"]', 'dumbbell', 'beginner', 3, '12-15', 2, 'Single arm, elbow braced on inner thigh'),
  ('Incline Dumbbell Curl', '["biceps"]', 'dumbbell', 'intermediate', 3, '10-12', 2, '45-60 degree incline, full stretch at bottom'),
  ('Spider Curl', '["biceps"]', 'barbell', 'intermediate', 3, '10-12', 2, 'Chest on incline bench, arms vertical, short ROM'),
  ('EZ-Bar Curl', '["biceps"]', 'barbell', 'beginner', 3, '10-12', 2, 'Angled grip reduces wrist stress'),
  ('21s (Bicep)', '["biceps"]', 'barbell', 'intermediate', 2, '21', 3, '7 bottom half + 7 top half + 7 full ROM'),

-- ARM EXERCISES - TRICEPS (10 exercises)
  ('Close-Grip Bench Press', '["triceps", "chest", "front_delts"]', 'barbell', 'intermediate', 4, '8-10', 2, 'Hands shoulder width, elbows tucked'),
  ('Tricep Pushdown', '["triceps"]', 'cable', 'beginner', 3, '12-15', 2, 'Rope or straight bar, elbows stable, full extension'),
  ('Overhead Tricep Extension', '["triceps"]', 'dumbbell', 'beginner', 3, '10-12', 2, 'Single or double dumbbell, full stretch at bottom'),
  ('Skull Crushers', '["triceps"]', 'barbell', 'intermediate', 3, '10-12', 2, 'Lower to forehead or overhead, elbow position critical'),
  ('Dips (Tricep Focused)', '["triceps", "chest"]', 'bodyweight', 'intermediate', 3, '8-12', 2, 'Upright torso, elbows back, full ROM'),
  ('Diamond Push-ups', '["triceps", "chest"]', 'bodyweight', 'beginner', 3, '10-15', 2, 'Hands form diamond, tricep emphasis'),
  ('Cable Overhead Extension', '["triceps"]', 'cable', 'beginner', 3, '12-15', 2, 'Rope attachment, step forward, stretch triceps'),
  ('JM Press', '["triceps"]', 'barbell', 'advanced', 3, '8-10', 2, 'Hybrid skull crusher and close-grip press'),
  ('Bench Dips', '["triceps"]', 'bodyweight', 'beginner', 3, '12-15', 2, 'Feet elevated or on floor, shoulder-width hands'),
  ('Single Arm Pushdown', '["triceps"]', 'cable', 'beginner', 3, '12-15', 2, 'Unilateral focus, address imbalances'),

-- CORE/ABS EXERCISES (8 exercises)
  ('Plank', '["core"]', 'bodyweight', 'beginner', 3, '30-60s', 3, 'Maintain neutral spine, full body tension'),
  ('Ab Wheel Rollout', '["core"]', 'bodyweight', 'advanced', 3, '8-12', 2, 'From knees or toes, control eccentric'),
  ('Hanging Leg Raise', '["core", "hip_flexors"]', 'bodyweight', 'intermediate', 3, '10-15', 2, 'Straight or bent legs, control swing'),
  ('Cable Crunch', '["core"]', 'cable', 'beginner', 3, '15-20', 2, 'Rope attachment, flex spine, squeeze abs'),
  ('Dead Bug', '["core"]', 'bodyweight', 'beginner', 3, '12-15', 3, 'Opposite arm and leg, maintain lower back contact'),
  ('Pallof Press', '["core"]', 'cable', 'intermediate', 3, '12-15', 3, 'Anti-rotation exercise, hold and press'),
  ('Russian Twist', '["core", "obliques"]', 'bodyweight', 'beginner', 3, '20-30', 3, 'Feet elevated, twist side to side, hold weight'),
  ('Bicycle Crunches', '["core", "obliques"]', 'bodyweight', 'beginner', 3, '20-30', 3, 'Controlled tempo, elbow to opposite knee'),

-- COMPOUND/OLYMPIC LIFTS (4 exercises)
  ('Power Clean', '["traps", "quads", "glutes", "core"]', 'barbell', 'advanced', 3, '3-5', 2, 'Explosive triple extension, catch in front rack'),
  ('Push Press', '["front_delts", "triceps", "quads"]', 'barbell', 'intermediate', 3, '6-8', 2, 'Slight knee dip, drive overhead explosively'),
  ('Snatch', '["traps", "quads", "glutes", "delts"]', 'barbell', 'advanced', 3, '2-3', 2, 'Full body explosive lift, wide grip, overhead catch'),
  ('Clean and Jerk', '["traps", "quads", "glutes", "delts"]', 'barbell', 'advanced', 3, '2-3', 2, 'Two-part lift, clean to front rack then jerk overhead');
